### ISSUE TITLE
possible game issues

### ISSUE THREAD

**Issue by mountnside** [mountnside/pj64-parallelrdp#6]
noticed a issue with Perfect Dark. hangs at one point using zilmar's rsp. should check with the other rsp.

**Comment by mountnside** [comment]
Potentially related.

https://github.com/project64/project64/issues/1872

**Comment by theboy181** [comment]
seem to of been blocked by you on Discord? Intentional?

**Comment by mountnside** [comment]
server members were able to be messaged, forgot to add you as friend

**Comment by mountnside** [comment]
closed due to being RSP related.
